"use client";

import Image from "next/image";
import Link from "next/link";

const A = "/assets/";

export default function OriginalContentSections() {
  return <main className="original-content">
    <section className="original-feature palestine-feature"><div><span className="eyebrow">Palestine still needs you!</span><h2>Help us save Palestinian families and orphans.</h2><p>The people of Palestine continue to suffer as famine looms and hunger becomes widespread. Families are being forced to live on less than a can of beans a day. Reports show malnourished newborns are so small that they weigh in at a little more than a kilo. Desperation for food is widespread, affecting the most vulnerable first, including orphaned children. Food assistance to combat famine is desperately needed.</p><p>Help us save Palestinian families and orphans with your Sadaqah today.</p><Link href="/crisis-and-emergencies/palestine" className="button button-pink">Donate Now</Link></div><div className="original-feature-image"><Image src={A + "appeal-gaza-food-water.jpg"} alt="Islamic Charity: Donate to Palestine" fill /></div></section>
    <section className="giving-section"><div className="original-heading"><span className="eyebrow">Islamic Giving</span><h2>Most Needed</h2><p>Give where your donation can make an immediate difference.</p></div><div className="giving-grid"><article><span>01</span><h3>Feed orphaned children in Gaza</h3><p>Feed orphaned children in Gaza for $65 and help reach others whose needs cannot wait.</p><Link href="/appeals/palestine-emergency">Give now →</Link></article><article><span>02</span><h3>Give Your Zakat to Gaza</h3><p>Let your Zakat reach families in Gaza who are relying on it for food, safety and survival.</p><Link href="/appeals/pay-your-zakat-to-gaza">Give now →</Link></article><article><span>03</span><h3>Give the Ultimate Sadaqah Jariyah</h3><p>Build a lasting source of mercy from $368 and let your charity continue long after you give.</p><Link href="/sadaqah-jariyah">Give now →</Link></article></div></section>
    <section className="promise original-promise"><div><span className="eyebrow">Our Promise To You:</span><h2>100% of your donation is used for the project.</h2><p>When you donate to a project, 100% of your donation (after merchant/banking fees) will be used for direct project costs and/or for donor engagement and raising funds to be reinvested in that project and/or other MATW projects.</p><p>Please see our <Link href="/100-donation-policy">100% donation policy</Link> for more information.</p></div><Image src={A + "policy100.aa465a15ceb7a44e6880.png"} alt="100% Donation Policy" width={220} height={220} /></section>
    <section className="legacy-story"><div className="original-heading"><span className="eyebrow">Ali Banat's Legacy</span><h2>Ali Banat’s Vision Was Clear: Build A Legacy To Help Every Needy Muslim Around The World.</h2><p>The MATW Project, started by Ali Banat as a legacy of compassion, has grown to reach millions of Muslims around the world. Through our collective efforts, we have been able to deliver life-saving aid, reaching over 19 million Muslims in some of the poorest and most vulnerable regions. With our help, MATW continues to provide food, clean water, medical aid, and shelter to those in desperate need. Our support is transforming lives, restoring hope, and building a better future for the Ummah. Together, we can make an even greater impact. Discover our impact reports, see the difference we are making, and continue supporting this life-changing cause. Every donation matters.</p><Link href="/annual-reports" className="button button-teal">See our impact here</Link></div><div className="legacy-mosaic"><Image src={A + "legacy11.81a5d3462eb095e5e34f.png"} alt="Islamic Charity founded by Ali Banat" width={500} height={500} /><Image src={A + "legacy12.753a665c4fe79de4b973.png"} alt="Muslim Charity founder Ali Banat" width={520} height={520} /><Image src={A + "legacy13.db02f131140dccb74bfa.png"} alt="100% Donation policy charity" width={500} height={500} /><Image src={A + "legacy14.4db13bce9dcade936ae7.png"} alt="Islamic Donations with MATW Project" width={500} height={500} /></div></section>
    <section className="original-sadaqah"><div><span className="eyebrow">Sadaqah Jariyah</span><h2>The gift that keeps giving.</h2><p>Sadaqah Jariyah, the gift that keeps giving, is a charitable practice with everlasting impact. Like Ali Banat, who left a legacy of Sadaqah Jariyah through MATW, you too can do the same, contributing to a mosque or water well in your name or for a loved one. This enduring act ensures positive change in the lives of those in need, planting the seeds of everlasting rewards.</p><div className="sadaqah-links"><Link href="/sadaqah-jariyah/build-a-masjid">Masjid</Link><Link href="/sadaqah-jariyah/build-a-water-well">Water Wells</Link><Link href="/sadaqah-jariyah/orphans">Orphans</Link><Link href="/sadaqah-jariyah/project-noor">Project Noor</Link></div></div><Image src={A + "appeal-masjid.jpg"} alt="General Masjid Donations" width={620} height={460} /></section>
    <section className="get-involved-original"><div className="original-heading"><span className="eyebrow">Get involved today!</span><h2>Build your legacy with MATW.</h2><p>Create a meaningful impact in this world and the hereafter through voluntary work, compassionate donations, and staying connected.</p></div><div className="involved-grid"><Link href="/annual-reports"><Image src={A + "view-our-reports.49a29687b1bc114c4c8c.jpg"} alt="Muslim Charity to help Muslims around the world" fill /><b>View our reports</b></Link><Link href="/volunteer"><Image src={A + "volunteer-with-us.efada332413c08a69ad3.jpg"} alt="Volunteer with MATW" fill /><b>Volunteer with us</b></Link><Link href="/all-appeals"><Image src={A + "all-appeals.6a4c1516fca9e55cb5ca.jpg"} alt="All appeals" fill /><b>All appeals</b></Link><Link href="https://www.instagram.com/matw_project/"><Image src={A + "Follow-Us-on-Instagram.e5b745d0fbf790c6fa2a.jpg"} alt="Follow us on Instagram" fill /><b>Follow us on Instagram</b></Link></div></section>
  </main>;
}
